name: git-crypt
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: git-crypt-unlock
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Install & unlock git-crypt
        run: |
          which git-crypt || sudo apt-get update --allow-releaseinfo-change && apt-get install -y git-crypt
          git config --global user.email "agarciafdz@gmail.com"
          git config --global user.name "agarciafdz"
          git status
          git clean -fdx
          git status
          git add .github/workflows/git-crypt.yml
          git stash
          echo "${{ secrets.GIT_CRYPT_KEY }}" | base64  --decode > ./production.env.key
          git-crypt unlock ./production.env.key
          rm ./production.env.key
      - name: trying to run all the tests
        run: |
          cd ./tutorials/plutus/
          echo "host is in: $(pwd)"
          sudo apt-get remove docker-compose
          sudo apt  install -y jq bc
          DOCKER_COMPOSE_VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | jq .name -r)
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          docker volume create --name=node-ipc
          docker-compose up --detach
          bash ./run_all_scripts.sh
      - name: stop the docker-compose server
        run: cd ./tutorials/plutus/ && docker-compose down
