name: git-crypt
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Test git-crypt-unlock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install & unlock git-crypt
        run: |
          which git-crypt || sudo apt install -y git-crypt
          echo "${{ secrets.GIT_CRYPT_KEY }}" | base64  --decode > ./production.env.key
          git-crypt unlock ./production.env.key
          rm ./production.env.key
          
      - name: trying to run all the tests
        run: |
          cd ./tutorials/plutus/
          docker-compose up --detach
          ./run_all_scripts.sh
