name: git-crypt
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Test git-crypt-unlock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install & unlock git-crypt
        run: |
          which git-crypt || sudo apt install -y git-crypt
          echo "GIT_CRYPT_KEY:'${{ secrets.GIT_CRYPT_KEY }}'"
          echo "${{ secrets.GIT_CRYPT_KEY }}" | base64  --decode > ./production.env.key
          git-crypt unlock ./production.env.key
          rm ./production.env.key
          
      - name: let's copy the golden master files
        run: |
          cp ./secrets/alice.addr ./temp/alice.addr
          cat ./temp/alice.addr
