name: git-crypt
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: git-crypt-unlock
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Install & unlock git-crypt
        run: |
          which git-crypt || sudo apt-get update --allow-releaseinfo-change && apt-get install -y git-crypt
          git config --global user.email "agarciafdz@gmail.com"
          git config --global user.name "agarciafdz"
          git status
          git clean -fdx
          git status
          git add .github/workflows/git-crypt.yml
          git stash
          echo "${{ secrets.GIT_CRYPT_KEY }}" | base64  --decode > ./production.env.key
          git-crypt unlock ./production.env.key
          rm ./production.env.key
      - name: trying to run all the tests
        run: |
          cd ./tutorials/plutus/
          docker volume create --name=node-ipc
          docker-compose up --detach
          ./run_all_scripts.sh
      - name: stop the docker-compose server
        run: cd ./tutorials/plutus/ && docker-compose down
